### ISSUE TITLE
All Access search is broken

### ISSUE THREAD

**Issue by parkerlreed** [mopidy/mopidy-gmusic#116]
Versions
mopidy-git 2.0.0.r37.gdf0d534-1
mopidy-gmusic-git 1.0.0.r2.g85e194c-1
python2-gmusicapi-git 9.0.0.r41.d35b8ce-1

````
INFO     Searching Google Play Music All Access for: Get Low
ERROR    GMusicBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 347, in search
    result = future.get()
  File "/usr/lib/python2.7/site-packages/pykka/future.py", line 299, in get
    exec('raise exc_info[0], exc_info[1], exc_info[2]')
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/library.py", line 300, in search
    query, uris)
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/library.py", line 340, in _search_all_access
    values[0], max_results=50)
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 31, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 117, in search_all_access
    return self.api.search_all_access(query, max_results=max_results)
AttributeError: 'Mobileclient' object has no attribute 'search_all_access'

````

**Comment by 5AMsan** [comment]
Same error on mine, here's my pip freeze output.
` pip freeze
appdirs==1.4.0
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
beautifulsoup4==4.4.1
certifi==2016.2.28
cffi==1.6.0
chardet==2.3.0
cryptography==1.3.1
decorator==4.0.9
enum34==1.1.4
funcsigs==1.0.2
future==0.15.2
gmusicapi==10.0.0
gpsoauth==0.2.0
httplib2==0.9.2
idna==2.1
ipaddress==1.0.16
MechanicalSoup==0.4.0
mock==2.0.0
Mopidy==2.0.0
Mopidy-GMusic==1.0.0
Mopidy-MusicBox-Webclient==2.2.0
Mopidy-Scrobbler==1.1.1
Mopidy-SoundCloud==2.0.2
Mopidy-Youtube==2.0.2
mutagen==1.31
MySQL-python==1.2.3
ndg-httpsclient==0.4.0
oauth2client==2.0.2
pafy==0.5.0
pbr==1.9.1
proboscis==1.2.6.0
protobuf==3.0.0b2
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.14
pycrypto==2.6.1
pycryptodome==3.4
pycurl==7.19.5
pygobject==3.14.0
Pykka==1.2.1
pylast==1.6.0
pyOpenSSL==16.0.0
python-dateutil==2.5.3
requests==2.10.0
RPi.GPIO==0.6.0a3
rsa==3.4.2
singledispatch==3.4.0.3
six==1.10.0
tornado==4.3
urllib3==1.9.1
validictory==1.0.1
youtube-dl==2016.5.1`

**Comment by jodal** [comment]
gmusicapi 10.0 renamed the search method in commit https://github.com/simon-weber/gmusicapi/commit/4419d0e10812d5b8861d0fafb45b74e8a1b63f27, breaking Mopidy-GMusic.

PR #117, which has now been merged, updates Mopidy-GMusic to work with gmusicapi 10.0 and enables search for accounts without All Access.

**Comment by parkerlreed** [comment]
````
mopidy-git 2.0.0.r37.gdf0d534-1
mopidy-gmusic-git 1.0.0.r12.g4fb9c8f-1
python2-gmusicapi-git 10.0.0.r2.7c5b5db-1
````

````
INFO     Starting Mopidy 2.0.0
INFO     Loading config from builtin defaults
INFO     Loading config from /home/parker/.config/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Disabled extension gmusic: gmusicapi>=10.0 required, but found gmusicapi 7.0.0 at /usr/lib/python2.7/site-packages
INFO     Enabled extensions: mpd, http, stream, m3u, softwaremixer, file, local
INFO     Disabled extensions: gmusic
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Starting Mopidy audio
INFO     Audio output set to "autoaudiosink"
INFO     Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, LocalBackend
INFO     No local library metadata cache found at /home/parker/.local/share/mopidy/local/library.json.gz. Please run `mopidy local scan` to index your local music library. If you do not have a local music collection, you can disable the local backend to hide this message.
INFO     Loaded 0 local tracks using json
INFO     Starting Mopidy core
INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
INFO     MPD server running at [::ffff:0.0.0.0]:6600
INFO     HTTP server running at [::ffff:127.0.0.1]:6680
INFO     Starting GLib mainloop
INFO     New MPD connection from [::ffff:127.0.0.1]:42302
````

**Comment by parkerlreed** [comment]
Ok that 7.0.0 was an extraneous folder but now gmusicapi is requiring MechSoup 0.4.0 but there is not git package on the AUR :/

````
INFO     Disabled extension gmusic: (MechanicalSoup 0.3.1 (/usr/lib/python2.7/site-packages), Requirement.parse('MechanicalSoup>=0.4.0'), set(['gmusicapi']))
````

python2-mechanicalsoup 0.3.1-5
